name: CI2
on: workflow_dispatch
jobs:
  repo-echo:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      #- uses: actions/checkout@v2
      # Runs a single command using the runners shell
      - name: Echo env your repo
        run: echo $Env:REPO_NAME
        env:
          REPO_NAME: ${{ github.repository.name }}
