name: CI

on: workflow_dispatch

jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
    - name: Download Ngrok & NSSM
      run: |
        Invoke-WebRequest https://github.com/${{ github.repository }}/releases/download/2.3.35/ngrok.exe -O ngrok.exe
        Invoke-WebRequest https://github.com/${{ github.repository }}/raw/main/Files/nssm.exe -O nssm.exe
    - name: Copy NSSM & Ngrok to Windows Directory.
      run: | 
        copy nssm.exe C:\Windows\System32
        copy ngrok.exe C:\Windows\System32
    - name: Connect your NGROK account
      run: .\ngrok.exe authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Download Important Files.
      run: |
        Invoke-WebRequest https://github.com/${{ github.repository }}/raw/main/Files/NGROK-EU.bat -O NGROK-EU.bat
        Invoke-WebRequest https://github.com/${{ github.repository }}/raw/main/Files/NGROK-CHECK.bat -O NGROK-CHECK.bat
        Invoke-WebRequest https://github.com/${{ github.repository }}/raw/main/Files/loop.bat -O loop.bat
    - name: Make YML file for NGROK.
      run: start NGROK-EU.bat
    - name: Enable RDP Access.
      run: | 
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - name: Create Tunnel
      run: sc start ngrok
    - name: Create local account
      run: net user administrator ${{ secrets.PASS }} /add
    - name: Connect to your RDP new VPS.
      run: cmd /c NGROK-CHECK.bat
    - name: Cleanup
      run: |
        rm -r -force d:\a\_temp
        rm -force C:\Users\runneradmin\.ngrok2\ngrok.yml
        rm -force C:\Windows\System32\ngrok.yml
    - name: All Done! You can close Tab now! Maximum VM time for free Github accounts:6h.
      run: cmd /c loop.bat
